name: break_clean
description: break_clean

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter



  # Service locator
  get_it: ^7.0.0

  # Bloc for state management
  flutter_bloc: ^7.0.0

  # Value equality
  equatable: ^2.0.0

  # Remote API
  http: ^0.13.1

  # Functional programming thingies
  dartz: ^0.10.0

  # Local cache
  shared_preferences: ^2.0.6

  #creating MOCKS  behavior verification, and stubbing.
  mockito: ^5.0.15

  #checks for an Active Internet connection
  internet_connection_checker: ^0.0.1+2

  #to handle offline/online connectivity
  flutter_offline: ^2.0.0
  provider: ^6.0.0
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.0






dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  #splash screen
  flutter_native_splash: ^1.2.3
# run: flutter clean && flutter pub get && flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#f0c828"
  image: assets/images/splash.png
  android: true
  ios: true



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/languages/


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
